#[build]
#  command = "npm start"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[edge_functions]]
  function = "wapp"
  path = "/"


# [[headers]]
#   for = "/*"
#   [headers.values]
#     X-Frame-Options = "DENY"
#     X-XSS-Protection = "1; mode=block"
#     Referrer-Policy = "same-origin"
#     X-Content-Type-Options = "nosniff"  
#     Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()"

[context.production.environment]
  NODE_VERSION = "18.12.1"